---
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE,
  comment    = "#>",
  fig.path   = "man/figures/",
  fig.retina = 3
)
```

# Bem-vindo(a) à nossa pesquisa!


Agradecemos por participar. Nesta pesquisa, perguntaremos sobre suas preferências em relação a diferentes tipos de café.

---

# Termo de Consentimento Livre e Esclarecido

Esta pesquisa está sendo conduzida por pesquisadores do Grupo de Pesquisa Café da Universidade de Brasília, sob a supervisão da Prof.ª Lívia de Lacerda de Oliveira. Não coletaremos nenhum dado identificável, como seu nome ou endereço. Toda a pesquisa levará aproximadamente de 10 a 15 minutos para ser concluída. Os dados são protegidos por senha com acesso exclusivo pela supervisora. Sua participação é voluntária e você pode interromper a pesquisa a qualquer momento.

Se desejar participar, por favor, responda às perguntas a seguir:

Tenho 18 anos ou mais

- Sim
- Não

Li e entendo as informações acima

- Sim
- Não

---

Você gosta de café?

- Sim!
- Um pouco
- Não :(

Com que frequência você bebe café?

- 2 vezes ao dia ou mais
- Uma vez ao dia
- Regularmente (quase todo dia)
- Ocasionalmente (até 3 vezes por semana)
-Raramente

Como você compra café mais frequentemente?

- Grãos verdes
- Grãos torrados
- Torrado e moído
- Em cápsulas
- Solúvel
- Bebida pronta

---

Antes de continuarmos, por favor selecione a opção que melhor descreve você: 

- Sou eu quem compra o café para minha casa
- Eu consumo café, mas não sou eu quem o compra para minha casa

